version: '3'
services:
    apache:
        image: fuzzy-palm-tree:latest
        build: ./
        ports:
            - "8090:80"
        volumes:
            - storage:/var/www/html/storage
        depends_on:
            - mysql
        environment:
            - DB_CONNECTION=mysql
            - DB_HOST="mysql"
            - DB_PORT="3306"
            - DB_DATABASE="partydos"
            - DB_USERNAME="user"
            - DB_PASSWORD="password
    mysql:
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: rootpass
            MYSQL_DATABASE: partydos
            MYSQL_USER: root
            MYSQL_PASSWORD: password
        ports:
            - "3306:3306"
        volumes:
            - mysql-data:/var/lib/mysql

volumes:
    mysql-data:
    storage:
