version: '3'
services:
    apache:
        image: fuzzy-palm-tree:latest
        build: ./
        ports:
            - "8090:80"
        volumes:
            - storage:/var/www/html/storage
        depends_on:
            - mysql
        environment:
            - DB_DATABASE=db
            - DB_USERNAME=user
            - DB_PASSWORD=pass
            - DB_CONNECTION=mysql
            - DB_HOST=mysql
            - APP_DEBUG=true
            - APP_KEY=base64:EOIbS8wLQldiGK0hXHlpntpFf+YJPBIiZv+BiFkFGts=
            - GOOGLE_CLIENT_ID=948023160451-shr6u6v41t8br28088q8iksditfp6bc6.apps.googleusercontent.com
            - GOOGLE_CLIENT_SECRET=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
            - GOOGLE_CLIENT_HD=nextly.nl
            - API_GATEWAY_TOKEN=4|Zv8eQbdJxQ7bK6mMpacbuRG5Dj3rpfWDm3XaXELM

    mysql:
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: rootpass
            MYSQL_DATABASE: db
            MYSQL_USER: user
            MYSQL_PASSWORD: pass
        ports:
            - "3306:3306"
        volumes:
            - mysql-data:/var/lib/mysql

volumes:
    mysql-data:
    storage:
