version: '3'
services:
    apache:
        image: fuzzy-palm-tree:latest
        build: ./
        ports:
            - "8080:80"
        volumes:
            - storage:/var/www/html/storage
        depends_on:
            - mysql
        environment:
            - DB_DATABASE=db
            - DB_USERNAME=user
            - DB_PASSWORD=pass
            - DB_CONNECTION=mysql
            - DB_HOST=mysql
            - APP_DEBUG=true
            - APP_KEY=base64:878JLq7tcZZbXgaUQOJBHcgwOBU5bhT3KeDb9tzGZGs=
    mysql:
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: rootpass
            MYSQL_DATABASE: db
            MYSQL_USER: user
            MYSQL_PASSWORD: pass
        ports:
            - "3306:3306"
        volumes:
            - mysql-data:/var/lib/mysql

volumes:
    mysql-data:
    storage:
