version: '3.9'
services:
  apache:
    labels:
      # Override or remove problematic labels
      - traefik.enable=true
      - traefik.http.routers.partydos.rule=Host(`partydos.app`)
      - traefik.http.routers.partydos.entrypoints=websecure
      - traefik.http.routers.partydos.tls=true
      - traefik.http.routers.partydos.tls.certresolver=letsencrypt
      - traefik.http.services.partydos.loadbalancer.server.port=80
