version: '3'
services:
    apache:
        image: fuzzy-palm-tree:latest
        build: ./
        ports:
            - "8090:80"
        volumes:
            - storage:/var/www/html/storage
        depends_on:
            - mysql
        environment:
            - DB_CONNECTION=mysql
            - DB_HOST="mysql"
            - DB_PORT="3306"
            - DB_DATABASE="db"
            - DB_USERNAME="root"
            - DB_PASSWORD="rootpass"
    mysql:
        image: mysql:latest
        environment:
            MYSQL_DATABASE: db
            MYSQL_PASSWORD: rootpass
        ports:
            - "3306:3306"
        volumes:
            - mysql-data:/var/lib/
        networks:
            - dokploy-network

volumes:
    mysql-data:
    storage:
