version: '3.9'
services:
    apache:
        image: fuzzy-palm-tree:latest
        build: ./
        container_name: laravel_app
        restart: always
        volumes:
            - storage:/var/www/html/storage
        depends_on:
            - mysql
        environment:
            - DB_CONNECTION=mysql
            - DB_HOST=mysql
            - DB_PORT=3306
            - DB_DATABASE=db
            - DB_USERNAME=root
            - DB_PASSWORD=rootpass
        networks:
            - dokploy-network
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.laravel.rule=Host(`partydos.app`)"
            - "traefik.http.routers.laravel.entrypoints=websecure"
            - "traefik.http.routers.laravel.tls.certresolver=letsencrypt"
            - "traefik.docker.network=dokploy-network"

    mysql:
        container_name: mysql
        image: mysql:latest
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=rootpass
            - MYSQL_DATABASE=db
            - MYSQL_USER=user
            - MYSQL_PASSWORD=pass
        volumes:
            - mysql-data:/var/lib/mysql
        networks:
            - dokploy-network

networks:
    dokploy-network:
        external: true

volumes:
    mysql-data:
    storage:
