version: '3.9'
services:
  apache-test:
    image: fuzzy-palm-tree:latest
    build: ./
    expose:
      - "80"
    volumes:
      - storage_test:/var/www/html/storage
    depends_on:
      - mysql-test
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=db
      - DB_USERNAME=root
      - DB_PASSWORD=rootpass
    networks:
      - dokploy-network

  mysql-test:
    container_name: mysql_test
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data_test:/var/lib/mysql
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true

volumes:
  storage_test:
  mysql_data_test:
